#!/bin/bash
# Switch the box's master audio output: hdmi | jack | usb | status
# Writes ~/.asoundrc so the ALSA "default" device (which Mixxx uses) points
# at the chosen card through the plug layer, then restarts Mixxx (the kiosk
# session respawns it). HDMI (vc4-hdmi) needs plug: it only accepts IEC958
# framing, raw hw: opens from PortAudio fail with "Sample format not
# supported". Cards are looked up BY NAME (the ALSA index order changes
# between boots), and djbox-audio.service re-applies the saved choice at
# boot before the kiosk starts.
set -u
RC=/home/dj/.asoundrc
STATE=/home/dj/.djbox-audio

card_of() {
    # $1 = pattern in `aplay -l`
    aplay -l 2>/dev/null | awk -v p="$1" '$0 ~ p {sub(":", "", $2); print $2; exit}'
}

write_rc() {
    cat > "$RC" <<EOF
# generated by djbox-audio.sh -- $1
pcm.!default {
    type plug
    slave.pcm "hw:$2,0"
}
ctl.!default {
    type hw
    card $2
}
EOF
    echo "$1" > "$STATE"
}

case "${1:-status}" in
    hdmi)
        c=$(card_of 'vc4-hdmi-0'); [ -n "$c" ] || { echo "no HDMI card"; exit 1; }
        write_rc hdmi "$c" ;;
    jack)
        c=$(card_of 'bcm2835 Headphones'); [ -n "$c" ] || { echo "no jack card (dtparam=audio=on?)"; exit 1; }
        write_rc jack "$c" ;;
    usb)
        c=$(aplay -l 2>/dev/null | grep '^card' | grep -viE 'vc4-hdmi|bcm2835' | head -1 | awk '{sub(":", "", $2); print $2}')
        [ -n "$c" ] || { echo "no USB sound card"; exit 1; }
        write_rc usb "$c" ;;
    status)
        echo "current: $(cat "$STATE" 2>/dev/null || echo unknown)"
        aplay -l 2>/dev/null | grep '^card'
        exit 0 ;;
    *)
        echo "usage: $0 hdmi|jack|usb|status"; exit 1 ;;
esac

echo "audio -> $1 (card $c)"
if [ "${2:-}" != "--no-restart" ]; then
    pkill -f 'mixxx --[f]ullScreen' || true
fi
