#!/bin/bash
# Switch the box's master audio output: hdmi | jack | usb | status
#
# HDMI on the Pi (vc4-hdmi) only takes IEC958-framed samples, so a raw hw:
# open from PortAudio fails with "Sample format not supported". The fix is a
# NAMED plug PCM in ~/.asoundrc ("hdmi_out"): PortAudio lists it as its own
# device and the plug layer does the conversion. Mixxx then just selects
# that device in soundconfig.xml -- and keeps it across restarts because it
# stores devices by name.
#
# jack = bcm2835 Headphones (hw), usb = first non-onboard card (hw).
# Mixxx must be STOPPED while soundconfig.xml is written, otherwise it
# overwrites the file on exit with the old device.
set -u
RC=/home/dj/.asoundrc
SC=/home/dj/.mixxx/soundconfig.xml
STATE=/home/dj/.djbox-audio

write_rc() {
    cat > "$RC" <<'EOF'
# generated by djbox-audio.sh
pcm.hdmi_out {
    type plug
    slave {
        pcm "hw:vc4hdmi0,0"
        rate 48000
        channels 2
    }
    hint { show on; description "HDMI-0 audio (plug)" }
}
pcm.!default {
    type plug
    slave.pcm "hw:Headphones,0"
}
EOF
}

# $1 = alsaHwDevice attr, $2 = name attr, $3 = portAudioIndex.
# The helper rebuilds the file when Mixxx left it without any device,
# which is what happens after it starts with no working output.
set_mixxx_device() {
    /usr/local/bin/djbox-mixxx-sounddevice.py "$1" "$2" "$3"
}

# Emits "<cardnum>|<Mixxx device name>". PortAudio names ALSA hw devices as
# "<card name>: <device name> (hw:N,0)", but Mixxx stores and matches them with
# that suffix stripped -- writing the suffixed form leaves it with no output
# device at all ("Mixxx was configured without any output sound devices").
usb_card() {
    aplay -l 2>/dev/null | grep '^card' | grep -viE 'vc4-hdmi|bcm2835' | head -1 \
        | python3 -c '
import re, sys
line = sys.stdin.read()
m = re.match(r"card (\d+): \S+ \[([^\]]+)\], device 0: [^\[]+\[([^\]]+)\]", line)
if m:
    print("%s|%s: %s" % (m.group(1), m.group(2), m.group(3)))
'
}

restart_mixxx() {
    [ "${2:-}" = "--no-restart" ] && return
    pkill -f 'mixxx --[f]ullScreen' || true
    # Wait for the old instance to fully exit before writing config: Mixxx
    # writes soundconfig.xml on shutdown and would clobber ours.
    for _ in $(seq 1 30); do
        pgrep -f 'mixxx --[f]ullScreen' >/dev/null || break
        sleep 0.5
    done
}

case "${1:-status}" in
    hdmi)
        restart_mixxx "$@"
        write_rc
        set_mixxx_device "hdmi_out" "hdmi_out" "9"
        echo hdmi > "$STATE"
        echo "audio -> HDMI (hdmi_out plug)" ;;
    jack)
        restart_mixxx "$@"
        write_rc
        set_mixxx_device "hw:0,0" "bcm2835 Headphones: -" "0"
        echo jack > "$STATE"
        echo "audio -> jack" ;;
    usb)
        info=$(usb_card)
        [ -n "$info" ] || { echo "no USB sound card"; exit 1; }
        c=${info%%|*}; n=${info#*|}
        restart_mixxx "$@"
        write_rc
        # PortAudio index of a hw: device matches its ALSA card number here
        set_mixxx_device "hw:$c,0" "$n" "$c"
        echo usb > "$STATE"
        echo "audio -> USB ($n, hw:$c,0)" ;;
    status)
        echo "current: $(cat "$STATE" 2>/dev/null || echo unknown)"
        grep -o 'name="[^"]*"' "$SC" | head -1
        aplay -l 2>/dev/null | grep '^card'
        exit 0 ;;
    *)
        echo "usage: $0 hdmi|jack|usb|status [--no-restart]"; exit 1 ;;
esac
# The kiosk session respawns Mixxx after the pkill above.
