obj-m := snd-usb-audio.o
snd-usb-audio-y := card.o clock.o endpoint.o fcp.o format.o helper.o implicit.o mixer.o mixer_quirks.o mixer_scarlett.o mixer_scarlett2.o mixer_us16x08.o mixer_s1810c.o pcm.o power.o proc.o quirks.o stream.o validate.o
snd-usb-audio-$(CONFIG_SND_USB_AUDIO_MIDI_V2) += midi2.o
snd-usb-audio-$(CONFIG_SND_USB_AUDIO_USE_MEDIA_CONTROLLER) += media.o
ccflags-y += -I$(src)
